- hosts: fermope
  tasks: 
  - name: criar arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1> Feito com o Terraform e ansible, alterando</h1>
  - name: criando servidor
    shell: "nohup busybox httpd -f -p 8080 &"
    